theme: jekyll-theme-minimal
title: Machine Learning for the Web
description:  Making Machine Learning a first-class web citizen
logo: https://avatars2.githubusercontent.com/u/42399997
show_downloads: false
github:
 is_user_page: false
 is_project_page: false
